/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../config/keys.ts" />
/// <reference path="../config/controls.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../objects/player.ts" />
/// <reference path="../objects/enemy.ts" />
/// <reference path="../objects/gameobject.ts" />
/// <reference path="../objects/vector2.ts" />
/// <reference path="../objects/laser.ts" />
/// <reference path="../managers/collision.ts" />
/// <reference path="../scenes/menu.ts" />
/// <reference path="../scenes/shooter.ts" /> 
//# sourceMappingURL=_reference.js.map